language: python
python:
  - 3.5
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8
# run tests
before_script:
  - flake8 .
script:
  - coverage run --source=app manage.py test

after_sucess:
  - CODECLIMATE_REPO_TOKEN=dd3780ba82be65f3f7582d0bf5148299f7bc9c7828da3efb674d1732ce7a5c88 codeclimate-test-reporter
