language: python
python:
  - 3.5
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# run tests
script:
  - coverage run manage.py test
  - python manage.py test

after_success:
  coveralls
