language: python
python:
  - 3.5
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8
# run tests
script:
  - coverage run --source=app manage.py test
  - flake8

after_success:
  coveralls
