# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170307_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
