# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170308_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
