# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170308_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='room',
            field=models.ManyToManyField(blank=True, to='app.Room'),
        ),
    ]
