# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170308_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='room',
            new_name='rooms',
        ),
    ]
