# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170308_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='rooms',
        ),
        migrations.AddField(
            model_name='event',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='app.Room'),
        ),
    ]
