# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170321_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
