# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170519_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Permission')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room')),
            ],
        ),
    ]
